import streamlit as st
import joblib
import re
import string
import numpy as np

# =====================================================
# PAGE CONFIG
# =====================================================

st.set_page_config(
    page_title="AI vs Human Content Detector",
    page_icon="🤖",
    layout="wide"
)

# =====================================================
# LOAD MODEL & VECTORIZER
# =====================================================

@st.cache_resource
def load_artifacts():
    model = joblib.load("models/best_model.pkl")
    vectorizer = joblib.load("models/tfidf_vectorizer.pkl")
    return model, vectorizer

model, vectorizer = load_artifacts()

# =====================================================
# TEXT CLEANING
# =====================================================

def clean_text(text):

    text = str(text).lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove punctuation
    text = text.translate(
        str.maketrans("", "", string.punctuation)
    )

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

# =====================================================
# TEXT ANALYTICS
# =====================================================

def calculate_text_metrics(text):

    words = text.split()

    word_count = len(words)

    char_count = len(text)

    sentence_count = max(
        len(re.findall(r"[.!?]+", text)),
        1
    )

    avg_word_length = (
        sum(len(word) for word in words) / word_count
        if word_count > 0 else 0
    )

    unique_words = len(set(words))

    vocabulary_diversity = (
        unique_words / word_count
        if word_count > 0 else 0
    )

    return {
        "word_count": word_count,
        "char_count": char_count,
        "sentence_count": sentence_count,
        "avg_word_length": avg_word_length,
        "vocabulary_diversity": vocabulary_diversity
    }

# =====================================================
# CONFIDENCE SCORE
# =====================================================

def get_confidence(model, X):

    try:
        score = model.decision_function(X)[0]

        abs_score = abs(score)

        if abs_score >= 2:
            confidence = "High"
        elif abs_score >= 1:
            confidence = "Medium"
        else:
            confidence = "Low"

        return confidence, score

    except:
        return "Unknown", 0

# =====================================================
# HEADER
# =====================================================

st.title("🤖 AI vs Human Content Detector")

st.markdown("""
Detect whether a piece of text is likely written by a Human or generated by AI using
Natural Language Processing (NLP) and Machine Learning.

**Model Used:** Linear SVM  
**Accuracy:** 99.62%  
**F1 Score:** 99.50%
""")

st.divider()

# =====================================================
# INPUT SECTION
# =====================================================

user_text = st.text_area(
    "✍️ Enter Text",
    height=250,
    placeholder="Paste your text here..."
)

# =====================================================
# ANALYZE BUTTON
# =====================================================

if st.button("🔍 Analyze Text", use_container_width=True):

    if user_text.strip() == "":
        st.warning("Please enter some text.")
        st.stop()

    cleaned_text = clean_text(user_text)

    text_vector = vectorizer.transform(
        [cleaned_text]
    )

    prediction = model.predict(text_vector)[0]

    confidence, decision_score = get_confidence(
    model,
    text_vector
    )

    metrics = calculate_text_metrics(
        user_text
    )

    st.divider()

    # =================================================
    # PREDICTION RESULT
    # =================================================

    st.subheader("Prediction Result")

    if prediction == 1:
        st.error("🤖 AI Generated Text")
    else:
        st.success("🧑 Human Written Text")

    st.subheader("Model Confidence")

    col1, col2 = st.columns(2)

    with col1:
        st.metric(
            "Confidence Level",
            confidence
        )

    with col2:
        st.metric(
            "Decision Score",
            f"{decision_score:.2f}"
        )

    if confidence == "High":
        st.success("The model is strongly confident in this prediction.")

    elif confidence == "Medium":
        st.warning("The model is moderately confident in this prediction.")

    else:
        st.info("The text is close to the decision boundary, so the prediction is less certain.")

    st.divider()

    # =================================================
    # TEXT ANALYTICS
    # =================================================

    st.subheader("📊 Text Analytics")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "Word Count",
            metrics["word_count"]
        )

        st.metric(
            "Character Count",
            metrics["char_count"]
        )

    with col2:
        st.metric(
            "Sentence Count",
            metrics["sentence_count"]
        )

        st.metric(
            "Average Word Length",
            f"{metrics['avg_word_length']:.2f}"
        )

    with col3:
        st.metric(
            "Vocabulary Diversity",
            f"{metrics['vocabulary_diversity']:.2f}"
        )

    st.divider()

    # =================================================
    # TEXT PREVIEW
    # =================================================

    st.subheader("📝 Submitted Text")

    st.write(user_text)

# =====================================================
# SIDEBAR
# =====================================================

st.sidebar.header("📌 Project Information")

st.sidebar.markdown("""
### AI vs Human Content Detection

This project uses:

- NLP Text Cleaning
- TF-IDF Vectorization
- Linear Support Vector Machine

### Dataset

AI vs Human Text Dataset

### Model Performance

- Accuracy: 99.62%
- F1 Score: 99.50%

### Technologies

- Python
- Scikit-Learn
- NLP
- Streamlit
""")